language: ruby
rvm:
  - 2.0.0-p598
  - 2.1.6

  # こういう書き方をすれば2.2.x系の最新版を使う
  - 2.2

  # 開発中のrubyのバージョン(いわゆるtrunk)
  - ruby-head

gemfile:
  - gemfiles/rails3_2.gemfile
  - gemfiles/rails4_0.gemfile
  - gemfiles/rails4_1.gemfile
  - gemfiles/rails4_2.gemfile

matrix:
  allow_failures:
  # 開発中のrubyでテストがこけることはあるだろうから許容する
  - rvm: ruby-head
